export const Info = [{
    id: 1,
    image: <img src="../../images/p1.jpeg" />,
    destTitle: "TAJ MAHAL",
    location: "Agra",
    fees: "7000",
    rating:5,
    description: "The Taj Mahal is considered to be the greatest architectural achievement in the whole range of Indo-Islamic architecture.The Mughal emperor Shah Jahan in memory of his favourite wife.",
},{
id : 2,
image: <img src="../../images/p2.jpeg" />,
destTitle: "EIFFEL TOWER",
location: "Paris",
fees: "10,000",
rating:3,
description: "  It was the world's tallest building at 1,024 feet . a unique panoramic view of Paris, The Tower also represents the magic of light. Its lighting, its sparkling lights, and its beacon shine and inspire dreams every evening.",
},{
id: 3,
image: <img src="../../images/p3.jpeg" />,
destTitle: "EGYTIAN PYRAMIDS",
location: "Egypt",
fees: "20,000",
rating:3.5,

description: "Pyramids today stand as a reminder of the ancient Egyptian glorification of life after death, and in fact, the pyramids were built as monuments to house the tombs of the pharaohs.",
},{
id: 4,
image: <img src="../../images/p4.jpeg" />,
destTitle: "STATUE OF LIBERTY",
location: "United States",
fees: "25,000",
rating:4.5,
description: "The Statue of Liberty. She is an icon, a national treasure, and one of the most recognizable figures in the world . She is the Statue of Liberty, a symbol of freedom, inspiration, and hope.",
},
{
    id: 5,
    image: <img src="../../images/p5.jpeg" />,
    destTitle: "COLOSSEUM",
    location: "Italy",
    fees: "2,00,000",
    rating:5,
    description: " The Colosseum is the largest amphitheater (meaning “theatre in the round”) in the world! Oval in shape, it measures 189m long, 156m wide and 50m high (about the height of a 12 storey building). This ancient sporting arena could easily fit a modern day football pitch inside!."
},
    {
        id: 6,
        image: <img src="../../images/p6.jpeg" />,
        destTitle: "OPERA HOUSE",
        location: "Austraila ",
        fees: "1,00,000",
        rating:3,
        description: "The Sydney Opera House constitutes a masterpiece of 20th century architecture. Its significance is based on its unparalleled design and construction; its exceptional engineering achievements and technological innovation and its position as a world-famous icon of architecture.",
    },
        {
            id: 7,
            image: <img src="../../images/p12.jpeg" />,
            destTitle: "HIMALAYAS",
            location: "Jammu & Kashmir",
            fees: "70,000",
            rating:3,
            description: "The Himalayas include the highest mountains in the world, and are known for their soaring heights, steep-sided jagged peaks, valleys, and alpine glaciers, deep river gorges, and a series of elevational belts that display different ecological associations of flora, fauna, and climate.",
        },{
                id: 8,
                image: <img src="../../images/p10.jpeg" />,
                destTitle: "GREAT WALL OF CHAIN",
                location: "China",
                fees: "1,20,000",
                rating:4.5,
                description: "The Great Wall is reputed as one of the seven construction wonders in the world not only for its long history, but its massive construction size, and its unique architectural style as well. A great army of manpower, composed of soldiers, prisoners, and local people, built the wall.",
        }

]; 